// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			shift(3), // id
			nil,      // (
			nil,      // )
			shift(4), // let
			nil,      // =
			shift(5), // get
			nil,      // ,
			nil,      // quotedstring
			nil,      // int
			nil,      // float
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			shift(3),     // id
			nil,          // (
			nil,          // )
			shift(4),     // let
			nil,          // =
			shift(5),     // get
			nil,          // ,
			nil,          // quotedstring
			nil,          // int
			nil,          // float
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: FuncCallList
			reduce(1), // id, reduce: FuncCallList
			nil,       // (
			nil,       // )
			reduce(1), // let, reduce: FuncCallList
			nil,       // =
			reduce(1), // get, reduce: FuncCallList
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // id
			shift(7), // (
			nil,      // )
			nil,      // let
			nil,      // =
			nil,      // get
			nil,      // ,
			nil,      // quotedstring
			nil,      // int
			nil,      // float
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			shift(8), // id
			nil,      // (
			nil,      // )
			nil,      // let
			nil,      // =
			nil,      // get
			nil,      // ,
			nil,      // quotedstring
			nil,      // int
			nil,      // float
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(10), // id
			nil,       // (
			nil,       // )
			shift(4),  // let
			nil,       // =
			shift(5),  // get
			nil,       // ,
			shift(12), // quotedstring
			shift(13), // int
			shift(14), // float
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: FuncCallList
			reduce(2), // id, reduce: FuncCallList
			nil,       // (
			nil,       // )
			reduce(2), // let, reduce: FuncCallList
			nil,       // =
			reduce(2), // get, reduce: FuncCallList
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(16), // id
			nil,       // (
			nil,       // )
			shift(18), // let
			nil,       // =
			shift(20), // get
			nil,       // ,
			shift(21), // quotedstring
			shift(22), // int
			shift(23), // float
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			nil,       // )
			nil,       // let
			shift(24), // =
			nil,       // get
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // ␚, reduce: Data
			reduce(10), // id, reduce: Data
			nil,        // (
			nil,        // )
			reduce(10), // let, reduce: Data
			nil,        // =
			reduce(10), // get, reduce: Data
			nil,        // ,
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // ␚, reduce: Data
			reduce(9), // id, reduce: Data
			shift(7),  // (
			nil,       // )
			reduce(9), // let, reduce: Data
			nil,       // =
			reduce(9), // get, reduce: Data
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: FuncCall
			reduce(5), // id, reduce: FuncCall
			nil,       // (
			nil,       // )
			reduce(5), // let, reduce: FuncCall
			nil,       // =
			reduce(5), // get, reduce: FuncCall
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // ␚, reduce: Data
			reduce(8), // id, reduce: Data
			nil,       // (
			nil,       // )
			reduce(8), // let, reduce: Data
			nil,       // =
			reduce(8), // get, reduce: Data
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // ␚, reduce: Data
			reduce(11), // id, reduce: Data
			nil,        // (
			nil,        // )
			reduce(11), // let, reduce: Data
			nil,        // =
			reduce(11), // get, reduce: Data
			nil,        // ,
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: Data
			reduce(12), // id, reduce: Data
			nil,        // (
			nil,        // )
			reduce(12), // let, reduce: Data
			nil,        // =
			reduce(12), // get, reduce: Data
			nil,        // ,
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // id
			nil,        // (
			reduce(10), // ), reduce: Data
			nil,        // let
			nil,        // =
			nil,        // get
			reduce(10), // ,, reduce: Data
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			shift(25), // (
			reduce(9), // ), reduce: Data
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(9), // ,, reduce: Data
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(26), // )
			nil,       // let
			nil,       // =
			nil,       // get
			shift(27), // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(28), // id
			nil,       // (
			nil,       // )
			nil,       // let
			nil,       // =
			nil,       // get
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(6), // ), reduce: DataList
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(6), // ,, reduce: DataList
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(16), // id
			nil,       // (
			nil,       // )
			shift(18), // let
			nil,       // =
			shift(20), // get
			nil,       // ,
			shift(21), // quotedstring
			shift(22), // int
			shift(23), // float
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(8), // ), reduce: Data
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(8), // ,, reduce: Data
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // id
			nil,        // (
			reduce(11), // ), reduce: Data
			nil,        // let
			nil,        // =
			nil,        // get
			reduce(11), // ,, reduce: Data
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // id
			nil,        // (
			reduce(12), // ), reduce: Data
			nil,        // let
			nil,        // =
			nil,        // get
			reduce(12), // ,, reduce: Data
			nil,        // quotedstring
			nil,        // int
			nil,        // float
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(10), // id
			nil,       // (
			nil,       // )
			shift(4),  // let
			nil,       // =
			shift(5),  // get
			nil,       // ,
			shift(12), // quotedstring
			shift(13), // int
			shift(14), // float
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(16), // id
			nil,       // (
			nil,       // )
			shift(18), // let
			nil,       // =
			shift(20), // get
			nil,       // ,
			shift(21), // quotedstring
			shift(22), // int
			shift(23), // float
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: FuncCall
			reduce(3), // id, reduce: FuncCall
			nil,       // (
			nil,       // )
			reduce(3), // let, reduce: FuncCall
			nil,       // =
			reduce(3), // get, reduce: FuncCall
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(16), // id
			nil,       // (
			nil,       // )
			shift(18), // let
			nil,       // =
			shift(20), // get
			nil,       // ,
			shift(21), // quotedstring
			shift(22), // int
			shift(23), // float
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			nil,       // )
			nil,       // let
			shift(33), // =
			nil,       // get
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(5), // ), reduce: FuncCall
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(5), // ,, reduce: FuncCall
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: FuncCall
			reduce(4), // id, reduce: FuncCall
			nil,       // (
			nil,       // )
			reduce(4), // let, reduce: FuncCall
			nil,       // =
			reduce(4), // get, reduce: FuncCall
			nil,       // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(34), // )
			nil,       // let
			nil,       // =
			nil,       // get
			shift(27), // ,
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(7), // ), reduce: DataList
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(7), // ,, reduce: DataList
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(16), // id
			nil,       // (
			nil,       // )
			shift(18), // let
			nil,       // =
			shift(20), // get
			nil,       // ,
			shift(21), // quotedstring
			shift(22), // int
			shift(23), // float
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(3), // ), reduce: FuncCall
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(3), // ,, reduce: FuncCall
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(4), // ), reduce: FuncCall
			nil,       // let
			nil,       // =
			nil,       // get
			reduce(4), // ,, reduce: FuncCall
			nil,       // quotedstring
			nil,       // int
			nil,       // float
		},
	},
}
