// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			shift(3), // id
			nil,      // (
			nil,      // )
			nil,      // quotedstring
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			shift(3),     // id
			nil,          // (
			nil,          // )
			nil,          // quotedstring
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: FuncCallList
			reduce(1), // id, reduce: FuncCallList
			nil,       // (
			nil,       // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // id
			shift(7), // (
			nil,      // )
			shift(8), // quotedstring
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: FuncCallList
			reduce(2), // id, reduce: FuncCallList
			nil,       // (
			nil,       // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: FuncCall
			reduce(3), // id, reduce: FuncCall
			shift(10), // (
			nil,       // )
			shift(8),  // quotedstring
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: DataList
			reduce(4), // id, reduce: DataList
			reduce(4), // (, reduce: DataList
			nil,       // )
			reduce(4), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(12), // id
			shift(14), // (
			nil,       // )
			shift(15), // quotedstring
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // ␚, reduce: Data
			reduce(8), // id, reduce: Data
			reduce(8), // (, reduce: Data
			nil,       // )
			reduce(8), // quotedstring, reduce: Data
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: DataList
			reduce(6), // id, reduce: DataList
			reduce(6), // (, reduce: DataList
			nil,       // )
			reduce(6), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(12), // id
			shift(14), // (
			nil,       // )
			shift(15), // quotedstring
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(17), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			shift(20), // (
			nil,       // )
			shift(21), // quotedstring
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(22), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(12), // id
			nil,       // (
			nil,       // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(8), // ), reduce: Data
			nil,       // quotedstring
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(24), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // ␚, reduce: Data
			reduce(9), // id, reduce: Data
			reduce(9), // (, reduce: Data
			nil,       // )
			reduce(9), // quotedstring, reduce: Data
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			shift(26), // (
			reduce(3), // ), reduce: FuncCall
			shift(21), // quotedstring
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(4), // (, reduce: DataList
			reduce(4), // ), reduce: DataList
			reduce(4), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(12), // id
			shift(14), // (
			nil,       // )
			shift(15), // quotedstring
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(8), // (, reduce: Data
			reduce(8), // ), reduce: Data
			reduce(8), // quotedstring, reduce: Data
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: DataList
			reduce(5), // id, reduce: DataList
			reduce(5), // (, reduce: DataList
			nil,       // )
			reduce(5), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(29), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // ␚, reduce: DataList
			reduce(7), // id, reduce: DataList
			reduce(7), // (, reduce: DataList
			nil,       // )
			reduce(7), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(6), // (, reduce: DataList
			reduce(6), // ), reduce: DataList
			reduce(6), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(12), // id
			shift(14), // (
			nil,       // )
			shift(15), // quotedstring
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(31), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(32), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			reduce(9), // ), reduce: Data
			nil,       // quotedstring
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			nil,       // (
			shift(33), // )
			nil,       // quotedstring
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(9), // (, reduce: Data
			reduce(9), // ), reduce: Data
			reduce(9), // quotedstring, reduce: Data
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(5), // (, reduce: DataList
			reduce(5), // ), reduce: DataList
			reduce(5), // quotedstring, reduce: DataList
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // id
			reduce(7), // (, reduce: DataList
			reduce(7), // ), reduce: DataList
			reduce(7), // quotedstring, reduce: DataList
		},
	},
}
