// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // FuncCallList
		2,  // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S1
		-1, // S'
		-1, // FuncCallList
		6,  // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S2
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S3
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S4
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S5
		-1, // S'
		-1, // FuncCallList
		9,  // FuncCall
		-1, // DataList
		11, // Data
	},
	gotoRow{ // S6
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S7
		-1, // S'
		-1, // FuncCallList
		15, // FuncCall
		17, // DataList
		19, // Data
	},
	gotoRow{ // S8
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S9
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S10
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S11
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S12
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S13
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S14
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S15
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S16
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S17
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S18
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S19
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S20
		-1, // S'
		-1, // FuncCallList
		15, // FuncCall
		-1, // DataList
		29, // Data
	},
	gotoRow{ // S21
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S22
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S23
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S24
		-1, // S'
		-1, // FuncCallList
		9,  // FuncCall
		-1, // DataList
		30, // Data
	},
	gotoRow{ // S25
		-1, // S'
		-1, // FuncCallList
		15, // FuncCall
		31, // DataList
		19, // Data
	},
	gotoRow{ // S26
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S27
		-1, // S'
		-1, // FuncCallList
		15, // FuncCall
		-1, // DataList
		32, // Data
	},
	gotoRow{ // S28
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S29
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S30
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S31
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S32
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S33
		-1, // S'
		-1, // FuncCallList
		15, // FuncCall
		-1, // DataList
		35, // Data
	},
	gotoRow{ // S34
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
	gotoRow{ // S35
		-1, // S'
		-1, // FuncCallList
		-1, // FuncCall
		-1, // DataList
		-1, // Data
	},
}
