version = "0.3.2"

[scripts]
setup = """
rustup target add aarch64-unknown-linux-gnu &&
rustup target add x86_64-unknown-linux-gnu &&
rustup target add x86_64-pc-windows-gnu &&
rustup target add x86_64-apple-darwin &&
rustup target add aarch64-apple-darwin
"""

xbuild = """
cross build --target aarch64-unknown-linux-gnu --release --locked --verbose &&
cross build --target x86_64-unknown-linux-gnu --release --locked --verbose &&
cross build --target x86_64-pc-windows-gnu --release --locked --verbose &&
cross build --target x86_64-apple-darwin --release --locked --verbose &&
cross build --target aarch64-apple-darwin --release --locked --verbose
"""

distmv.generic = """
cp target/aarch64-unknown-linux-gnu/release/orion ./dist/orion-aarch64-unknown-linux-gnu &&
cp target/x86_64-unknown-linux-gnu/release/orion ./dist/orion-x86_64-unknown-linux-gnu &&
cp target/x86_64-pc-windows-gnu/release/orion.exe ./dist/orion-x86_64-pc-windows-gnu.exe &&
cp target/x86_64-apple-darwin/release/orion ./dist/orion-x86_64-apple-darwin &&
cp target/aarch64-apple-darwin/release/orion ./dist/orion-aarch64-apple-darwin
"""
distmv.targets.windows = """
cp target\\aarch64-unknown-linux-gnu\\release\\orion .\\dist\\orion-aarch64-unknown-linux-gnu &&
cp target\\x86_64-unknown-linux-gnu\\release\\orion .\\dist\\orion-x86_64-unknown-linux-gnu &&
cp target\\x86_64-pc-windows-gnu\\release\\orion.exe .\\dist\\orion-x86_64-pc-windows-gnu.exe &&
cp target\\x86_64-apple-darwin\\release\\orion .\\dist\\orion-x86_64-apple-darwin &&
cp target\\aarch64-apple-darwin\\release\\orion .\\dist\\orion-aarch64-apple-darwin
"""
distmv.targets.macos = """
cp target/aarch64-unknown-linux-gnu/release/orion ./dist/orion-aarch64-unknown-linux-gnu &&
cp target/x86_64-unknown-linux-gnu/release/orion ./dist/orion-x86_64-unknown-linux-gnu &&
cp target/x86_64-pc-windows-gnu/release/orion.exe ./dist/orion-x86_64-pc-windows-gnu.exe &&
cp target/x86_64-apple-darwin/release/orion ./dist/orion-x86_64-apple-darwin &&
cp target/aarch64-apple-darwin/release/orion ./dist/orion-aarch64-apple-darwin
"""
distmv.targets.linux = """
cp target/aarch64-unknown-linux-gnu/release/orion ./dist/orion-aarch64-unknown-linux-gnu &&
cp target/x86_64-unknown-linux-gnu/release/orion ./dist/orion-x86_64-unknown-linux-gnu &&
cp target/x86_64-pc-windows-gnu/release/orion.exe ./dist/orion-x86_64-pc-windows-gnu.exe &&
cp target/x86_64-apple-darwin/release/orion ./dist/orion-x86_64-apple-darwin &&
cp target/aarch64-apple-darwin/release/orion ./dist/orion-aarch64-apple-darwin
"""
