[package]
name = "orion"
version = "0.1.0"
edition = "2021"
authors = ["ArnabRollin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
clap_complete = "4.5.1"
orion_lib = "4.0.0"
