# https://taskfile.dev

version: "3"

vars:
  GRAMMAR_FILE: orion.md
  FILE: _examples/main.or

tasks:
  grammar:
    cmd: "gogll {{.GRAMMAR_FILE}}"
    silent: true

  grammar_verbose:
    cmd: "gogll -v {{.GRAMMAR_FILE}}"
    silent: true

  dev:
    deps:
      - grammar
    cmd: "go run . ior {{.FILE}} -v5"
    interactive: true

  dev_verbose:
    deps:
      - grammar_verbose
    cmd: "go run . ior {{.FILE}} -v5"
    interactive: true

  pre:
    deps:
      - grammar
    cmd: "go run . ior {{.FILE}}"
    interactive: true

  pre_verbose:
    deps:
      - grammar_verbose
    cmd: "go run . ior {{.FILE}}"
    interactive: true

  encode:
    deps:
      - grammar
    cmd: "go run . encode {{.FILE}}"
  
  encode_verbose:
    deps:
      - grammar_verbose
    cmd: "go run . encode {{.FILE}} -v5"

  test:
    deps:
      - grammar
    cmd: "go test ./..."

  bench:
    deps:
      - grammar
    cmd: "go test -benchmem -run=^$ -bench=./... ./..."
