# https://taskfile.dev

version: "3"

vars:
  GRAMMAR_DIR: lib
  GRAMMAR_FILE: orion.md

tasks:
  grammar:
    cmd: "cd {{.GRAMMAR_DIR}} && gogll {{.GRAMMAR_FILE}}"
    silent: true

  grammar_verbose:
    cmd: "cd {{.GRAMMAR_DIR}} && gogll -v {{.GRAMMAR_FILE}}"
    silent: true

  dev:
    deps:
      - grammar
    cmd: "go run . ior _examples/main.or -v6"
    interactive: true

  dev_verbose:
    deps:
      - grammar_verbose
    cmd: "go run . ior _examples/main.or -v6"
    interactive: true

  pre:
    deps:
      - grammar
    cmd: "go run . ior _examples/main.or"
    interactive: true

  pre_verbose:
    deps:
      - grammar_verbose
    cmd: "go run . ior _examples/main.or"
    interactive: true
