name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Bonnie
        run: cargo install bonnie

      - name: Run tests
        id: test
        run: cargo test --verbose

      - name: Build
        if: steps.test.outcome == 'success'
        run: bonnie setup && bonnie xbuild && mkdir dist && bonnie distmv

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*